language: node_js
node_js:
  - '10'
  - '8'
  - '6'
notifications:
  email: false
cache:
  directories:
    - node_modules
install: npm install
script:
  - npm run test
  - npm run build
after_success: npm run coverage
